---
Gemfile:
  use_litmus: true
  optional:
    ":development":
    - gem: github_changelog_generator
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')
    - gem: puppet_litmus
      git: https://github.com/puppetlabs/puppet_litmus
      ref: main
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.5.0')
    - gem: bolt
      version: '2.32.0'
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.5.0')
    - gem: puppet-resource_api
.pdkignore:
  paths:
    - '/dev/'
.github/workflows/pr_test.yml:
  unmanaged: true
.github/workflows/nightly.yml:
  unmanaged: false
  slack-notifications: false
.rubocop.yml:
  default_configs:
    Lint/ScriptPermission:
      Enabled: false
.travis.yml:
  deploy_to_forge:
    enabled: false
  remove_includes:
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
spec/spec_helper.rb:
  mock_with: ':rspec'
  strict_level: ':error'
  spec_overrides:
    - 'RSpec.configure { |c| c.fail_fast = true }'
spec/default_facts.yml:
  extra_facts:
    abide_uefi_boot: 'false'
    abide_coredump:
      unit_file_loaded: 'false'
      is_active: 'unknown'
      unit_file_exists: 'true'
      is_enabled: 'false'
